# Generated by Django 5.1 on 2026-05-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('employee_id', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('years_of_service', models.IntegerField(default=0)),
                ('job_clarity', models.IntegerField(blank=True, null=True)),
                ('skill_utilization', models.IntegerField(blank=True, null=True)),
                ('career_growth', models.IntegerField(blank=True, null=True)),
                ('training_support', models.IntegerField(blank=True, null=True)),
                ('supervisor_support', models.IntegerField(blank=True, null=True)),
                ('communication', models.IntegerField(blank=True, null=True)),
                ('recognition', models.IntegerField(blank=True, null=True)),
                ('feedback_received', models.IntegerField(blank=True, null=True)),
                ('work_balance', models.IntegerField(blank=True, null=True)),
                ('workplace_safety', models.IntegerField(blank=True, null=True)),
                ('facilities', models.IntegerField(blank=True, null=True)),
                ('team_collaboration', models.IntegerField(blank=True, null=True)),
                ('salary_satisfaction', models.IntegerField(blank=True, null=True)),
                ('benefits', models.IntegerField(blank=True, null=True)),
                ('on_time_payment', models.IntegerField(blank=True, null=True)),
                ('overall_satisfaction', models.IntegerField(blank=True, null=True)),
                ('improvements', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
