# Generated by Django 4.2 on 2026-06-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('years_of_service', models.IntegerField(blank=True, null=True)),
                ('asset_liked', models.TextField(blank=True, null=True)),
                ('asset_suggestions', models.TextField(blank=True, null=True)),
                ('cleanliness_aesthetics', models.IntegerField(blank=True, null=True)),
                ('external_appearance', models.IntegerField(blank=True, null=True)),
                ('internal_cleanliness', models.IntegerField(blank=True, null=True)),
                ('facility_condition', models.IntegerField(blank=True, null=True)),
                ('space_utilization', models.IntegerField(blank=True, null=True)),
                ('security_service', models.IntegerField(blank=True, null=True)),
                ('light_air_quality', models.IntegerField(blank=True, null=True)),
                ('maintenance_care', models.IntegerField(blank=True, null=True)),
                ('facility_suggestions', models.TextField(blank=True, null=True)),
                ('logistics_service_speed', models.IntegerField(blank=True, null=True)),
                ('vehicle_readiness', models.IntegerField(blank=True, null=True)),
                ('travel_time', models.IntegerField(blank=True, null=True)),
                ('driver_conduct', models.IntegerField(blank=True, null=True)),
                ('travel_safety', models.IntegerField(blank=True, null=True)),
                ('logistics_suggestions', models.TextField(blank=True, null=True)),
                ('vehicle_registration', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenance_quality', models.IntegerField(blank=True, null=True)),
                ('service_speed', models.IntegerField(blank=True, null=True)),
                ('staff_behavior', models.IntegerField(blank=True, null=True)),
                ('liked_service', models.TextField(blank=True, null=True)),
                ('improvement_needs', models.TextField(blank=True, null=True)),
                ('overall_satisfaction', models.IntegerField(blank=True, null=True)),
                ('general_comments', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
