# Generated by Django 4.2 on 2026-05-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('stakeholder_type', models.CharField(blank=True, max_length=200)),
                ('stakeholder_other', models.CharField(blank=True, max_length=200)),
                ('sector', models.CharField(blank=True, max_length=200)),
                ('minister_office', models.CharField(blank=True, max_length=200)),
                ('executive_director', models.CharField(blank=True, max_length=200)),
                ('crop_development', models.CharField(blank=True, max_length=200)),
                ('natural_resource', models.CharField(blank=True, max_length=200)),
                ('livestock', models.CharField(blank=True, max_length=200)),
                ('investment', models.CharField(blank=True, max_length=200)),
                ('provider_name', models.CharField(blank=True, max_length=200)),
                ('service_duration', models.IntegerField(default=0)),
                ('service_types', models.TextField(blank=True)),
                ('other_service', models.CharField(blank=True, max_length=200)),
                ('ease_of_access', models.IntegerField(blank=True, null=True)),
                ('staff_respect', models.IntegerField(blank=True, null=True)),
                ('staff_clarity', models.IntegerField(blank=True, null=True)),
                ('fast_response', models.IntegerField(blank=True, null=True)),
                ('accurate_service', models.IntegerField(blank=True, null=True)),
                ('clear_info', models.IntegerField(blank=True, null=True)),
                ('timely_service', models.IntegerField(blank=True, null=True)),
                ('met_expectations', models.IntegerField(blank=True, null=True)),
                ('overall_satisfaction', models.IntegerField(blank=True, null=True)),
                ('improvement', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
